version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: anymind
      POSTGRES_PASSWORD: anymind
      POSTGRES_DB: anymind_db
